// <auto-generated />
using System;
using EquipmentForRent.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EquipmentForRent.Migrations
{
    [DbContext(typeof(EquipmentRentContext))]
    partial class EquipmentRentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipmentForRent.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ClientId")
                        .HasName("PK__Client__E67E1A04541D0855");

                    b.HasIndex(new[] { "Login" }, "UQ__Client__5E55825B2F9A3948")
                        .IsUnique();

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("EquipmentForRent.Models.DefaultImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("ImageData");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageName");

                    b.HasKey("ImageID")
                        .HasName("PK__DefaultImage__3F77A23D");

                    b.ToTable("DefaultImages");
                });

            modelBuilder.Entity("EquipmentForRent.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<int>("LessorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EquipmentId");

                    b.HasIndex("LessorId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("EquipmentForRent.Models.Lessor", b =>
                {
                    b.Property<int>("LessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LessorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessorId"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("LessorId")
                        .HasName("PK__Lessor__BB9D81E7192D8589");

                    b.HasIndex(new[] { "Login" }, "UQ__Lessor__5E55825B3D8D5AC8")
                        .IsUnique();

                    b.ToTable("Lessor", (string)null);
                });

            modelBuilder.Entity("EquipmentForRent.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("ClientID");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    b.Property<int>("LessorId")
                        .HasColumnType("int")
                        .HasColumnName("LessorID");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OrderId")
                        .HasName("PK__Order__C3905BAF4F37B495");

                    b.HasIndex("ClientId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("LessorId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("EquipmentForRent.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("ClientID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<int>("LessorId")
                        .HasColumnType("int")
                        .HasColumnName("LessorID");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("Rating");

                    b.Property<string>("ReviewText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReviewText");

                    b.HasKey("ReviewId")
                        .HasName("PK__Review__D7D8F9223A1F82BC");

                    b.HasIndex("ClientId");

                    b.HasIndex("LessorId");

                    b.HasIndex("OrderId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EquipmentForRent.Models.Equipment", b =>
                {
                    b.HasOne("EquipmentForRent.Models.Lessor", "Lessor")
                        .WithMany("Equipment")
                        .HasForeignKey("LessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lessor");
                });

            modelBuilder.Entity("EquipmentForRent.Models.Order", b =>
                {
                    b.HasOne("EquipmentForRent.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK__Order__ClientID__412EB0B6");

                    b.HasOne("EquipmentForRent.Models.Equipment", "Equipment")
                        .WithMany("Orders")
                        .HasForeignKey("EquipmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Order__Equipment__4316F928");

                    b.HasOne("EquipmentForRent.Models.Lessor", "Lessor")
                        .WithMany("Orders")
                        .HasForeignKey("LessorId")
                        .IsRequired()
                        .HasConstraintName("FK__Order__LessorID__4222D4EF");

                    b.Navigation("Client");

                    b.Navigation("Equipment");

                    b.Navigation("Lessor");
                });

            modelBuilder.Entity("EquipmentForRent.Models.Review", b =>
                {
                    b.HasOne("EquipmentForRent.Models.Client", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK__Review__ClientID__5D6D4F8B");

                    b.HasOne("EquipmentForRent.Models.Lessor", "Lessor")
                        .WithMany("Reviews")
                        .HasForeignKey("LessorId")
                        .IsRequired()
                        .HasConstraintName("FK__Review__LessorID__5E5F0003");

                    b.HasOne("EquipmentForRent.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Lessor");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EquipmentForRent.Models.Client", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("EquipmentForRent.Models.Equipment", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EquipmentForRent.Models.Lessor", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
